# Original claims and revised evidence

This short crosswalk links the rewritten manuscript to result commit 87110da. It does not revise the preserved original manuscript or reclassify historical results. HF denotes Hospital-first; N denotes tract-normalized modeled burden. All intervals below are paired across the same 32 realizations.

| Original or superseded claim | Revised claim | Actual evidence and manuscript location |
|---|---|---|
| Hospital-first is the fastest or generally best restoration policy. | Two recovered weighted-priority sequences have small mean population-burden advantages; no universal winner is identified. | Balanced/HospFirst ΔN vs HF −0.295/−0.166 h, about 0.67%/0.38%; hospital/T80/makespan intervals span zero. Section 3.1, Table 2. |
| Three GA outputs represent optimized or best restoration policies. | Balanced/HospFirst are reconstructed deterministic initializers; Efficiency is a retained finite-budget search candidate. None is a demonstrated global optimum. | Same-objective scoring and retained histories, Supplement S2/Table S3/Figure S1. Different-objective fitness values are not cross-compared. |
| Simple HF outperformance is explained entirely by mismatch between GA fitness and T80. | First correct inferior candidate retention; then distinguish the surrogate from source-gated burden. The old HF superiority narrative no longer holds. | HospFirst own fitness 0.916459946176 vs HF0.916319981609; population ΔN−0.166 h; hospital Δ−0.022 h with interval crossing zero. Sections 2.5/4.1. |
| Earlier vulnerability-weighted T80 or lower inequality means greater equity. | Absolute group burdens, high–low gaps, and Gini measure different properties. No equity optimization is claimed. | Efficiency Gini0.1765 vs HF0.2187 while every group worsens; HospFirst improves Q4 by0.413 h but increases Q1 by0.117 h. Section 3.2/Figure 2. |
| All three GA policies worsen all four vulnerability groups. | Balanced improves all four group means; HospFirst shifts mean burden toward Q1 and away from Q4. Efficiency still worsens all four. | Fixed Q1–Q4 absolute levels and paired effects, Section 3.2. |
| Mapping supports actual customer supply or is generally robust. | Official evidence supports candidates; equal shares and named-system attachments remain assumptions. Overall contrast directions persist in two fixed-decision stresses, while group relations change. | λ=0.5/1/2; Efficiency signed Q4−Q1 mean +0.495/−1.388/−3.540 h. Sections 2.2/2.7/3.3. No true-share or downstream-damage validation. |
| Restoration assumptions mainly alter absolute recovery time. | Relative severe-damage workload can change the magnitude of policy costs. | Efficiency population excess vs HF rises15.076→26.245 h; change11.169 [9.303,12.880] h. Section 3.3/Table 3. |
| Modeled burden hours are resident outage hours; population metrics all measure the same average. | Normalized service-access deficit is a model quantity; full-population and population×resolved-mass weighting are distinct estimands. | Denominators3,520,382 people and3,426,254.42 population–candidate-mass units. Section 2.6/Eq.2/S3.1. |
| No effect or missing recovery may be classified as neutral. | Twelve fully unresolved tracts remain unknown, with NA normalized burden and direction probability. | 51,770 people,1.45% of full domain; never near-zero. Sections 2.2/2.6/Figure 3. |
| One population percentage describes who is delayed in every realization. | Classification of tract mean effects differs from classifying every realization then averaging. | Efficiency baseline worsened80.07% by mean effects vs76.57% realization-first mean; DS4×2 93.33% vs75.33%. Section 3.2–3.3/S3.2. |
| Crew or source scenarios are verified actual LA operations; historical times validate tract recovery. | Fixed57 pooled crews and21 reference sources define conditional operations. Capacity and delivered-power constraints remain outside scope. | Sections 2.1/2.3/2.4/4.3. No crew-count or power-flow validation is claimed. |
| Four policy points establish an efficiency–equity optimal frontier or a single-coefficient effect. | Four fixed policy bundles provide conditional distributional examples, not an optimized frontier or isolated equity intervention. | Multiple coefficient changes; paired burden/logistics evidence. Sections 2.5/4.1/4.3/5. |

The revised Results, Discussion, and Conclusion rely on these bounded claims. They do not reuse old 92-node rankings, percolation findings, composite hotspots, clustering, or historical recovery curves as new scientific evidence.
