"""Complete QA from saved linkage records after an audit-path variable collision."""
import pandas as pd,json,pyogrio,numpy as np,time
from source_audit import OUT,sha,dump
S=OUT/'sources';p=S/'LARIAC4_BUILDINGS_2014.zip';u='/vsizip/'+str(p).replace(chr(92),'/')+'/LARIAC4_BUILDINGS_2014/LARIAC4_BUILDINGS_2014.gdb';info=pyogrio.read_info(u,layer='LARIAC4_BUILDINGS_2014');ids=[];invalid=0;building=0
for offset in range(0,info['features'],300000):
 d=pyogrio.read_dataframe(u,layer='LARIAC4_BUILDINGS_2014',skip_features=offset,max_features=300000,columns=['CODE','BLD_ID']);d=d.loc[d.CODE.eq('Building')];ids.extend(d.BLD_ID.astype('string').str.strip().tolist());invalid+=int((~d.geometry.is_valid).sum());building+=len(d)
ids=pd.Series(ids,dtype='string');duplicated=int(ids.duplicated(keep=False).sum());records=[]
for p in sorted((S/'age_linkage').glob('*.csv.gz')):records.append(pd.read_csv(p,dtype={'BLD_ID':str}))
link=pd.concat(records,ignore_index=True);a=pd.read_csv(OUT/'BUILDING_AGE_ALL_USE_TRACTS.csv');q={'old_source_sha256':sha(S/'LARIAC4_BUILDINGS_2014.zip'),'new_source_sha256':sha(S/'LARIAC6_Buildings_2020.gdb.zip'),'2014_raw_records':info['features'],'2014_building_records':building,'2014_duplicate_ID_records_withheld':duplicated,'invalid2014_repaired':invalid,'2020_unique_outline_records':len(link),'unique_id_and_IoU_accepted':int(link.age_transfer_accepted.sum()),'unique_id_geometry_mismatch':int((link.has_unique2014_id&~link.age_transfer_accepted).sum()),'no_unique2014_id':int((~link.has_unique2014_id).sum()),'age_coverage_quantiles':a.all_use_age_coverage.quantile([0,.01,.5,.99,1]).to_dict(),'missing_age_area_not_imputed':True,'share_is_complete_all_buildings':False,'source_age_type':'parcel-assessor YearBuilt1 associated with building outline; not validation of actual construction year and not BRAILS predictions','area_weighting':'sum of distinct clipped outline areas; compare with LARIAC union overlap audit; no inferred floor area','unobserved_age_sensitivity':'lower=observed pre1970/total area; upper=(observed pre1970+missing-age area)/total; not point imputations','full_linkage_chunks':len(records),'qa_recovery':'Original extraction completed all linkage records and tract CSVs, then failed while hashing a shadowed path variable. QA reconstructed from retained outputs; no physical stages rerun.'};dump('BUILDING_AGE_QA.json',q);print('AGE_QA',q,flush=True)
