from pathlib import Path
import pandas as pd,networkx as nx,json
from r1_topology_robustness import characterize_topology
r=Path.cwd();o=r/'Revision_Mapping_Gate';s=pd.read_csv(r/'Data/source_nodes_core_expanded.csv',dtype={'ID':str});s=s[s.level.eq('Core')].copy();e=pd.read_csv(r/'Data/substation_graph_CEC_edges_expanded.csv',dtype={'u':str,'v':str});g=nx.from_pandas_edgelist(e,'u','v')
t=characterize_topology(g,s.ID);t.to_csv(o/'JULY92_TOPOLOGICAL_REDUNDANCY.csv');print(t[['single_source','single_path','single_upstream_station','disconnected']].sum().to_dict());print(t[t.single_path|t.single_upstream_station][['minimum_edge_source_cut','minimum_node_source_cut','articulation_dependencies']].to_string())
# Evidence classes: do not equate site identity with confirmed injected supply.
detail={
'300829':('named_transmission_station','SCE ICA/GNA named Gould; LA100 ch6 network appendix names GOULD','SCE_ICA_Layer_18_Substations.csv; LA100_ch6.txt','high identity; limited exogenous-source evidence','Imported power at this precise July node and availability not established'),
'301541':('named_upstream_system','SCE Mesa220/66 system and station; not a generator identity','SCE_ICA_Layer_18_Substations.csv','high identity; moderate upstream-role context','System label does not establish unlimited external injection'),
'305984':('named_upstream_system','SCE Rio Hondo named station/system; not generation evidence','SCE_ICA_Layer_18_Substations.csv','high identity; moderate upstream-role context','Incoming supply, outages and injection limits not identified'),
'307693':('documented_transmission_interface','Adelanto-Rinaldi500kV line endpoints and rating; LA100 transmission corridor','Adelanto_Rinaldi_MND_2025.pdf p9; LA100_ch6.txt','high corridor identity; conditional supply role','Bus partition, dispatch and import availability absent'),
'306489':('documented_import_complex_unresolved_bus','LA100 identifies Pacific DC Intertie import at Sylmar','LA100_ch6.txt line3304','high complex identity; limited East crosswalk','No explicit East/West to converter/bus crosswalk; not two independently confirmed injections'),
'310199':('documented_import_complex_unresolved_bus','LA100 identifies Pacific DC Intertie import at Sylmar','LA100_ch6.txt line3304','high complex identity; limited West crosswalk','No explicit East/West to converter/bus crosswalk'),
'307039':('legacy_generation_proxy_unconfirmed_bus','July source table names Alamitos generation proxy; retained public candidate identity insufficient for plant/bus availability','Data/source_nodes_core_expanded.csv','legacy definition only for injection','No retained EIA plant-to-July-bus crosswalk; no current availability claim'),
'309703':('legacy_generation_proxy_unconfirmed_bus','July source table names El Segundo generation proxy','Data/source_nodes_core_expanded.csv','legacy definition only for injection','No retained plant/bus crosswalk; do not infer from name'),
'304450':('generation_area_identity_ambiguous','LA100 identifies Harbor generation site; July HARBORGEN Owner=SCE differs from LADWP site context','LA100_ch6.txt PDF67; Data/working_area_substations_with_fragility.csv','generation site supported; exact July identity ambiguous','Do not merge HARBORGEN and RS-Q or assert independently available generation'),
'307373':('documented_generation_site','LA100 names Haynes in-basin gas generation site','LA100_ch6.txt PDF67','high named site; limited bus availability','Historical generation presence not guaranteed injection during modeled earthquake'),
'308540':('legacy_generation_proxy_unconfirmed_bus','July source table names Long Beach generation proxy','Data/source_nodes_core_expanded.csv','legacy definition only for injection','No retained current plant/bus/dispatch crosswalk'),
'309553':('generation_complex_receiving_node','LA100 Scattergood generation; LAX EA describes Scattergood138kV/230kV connections','LA100_ch6.txt PDF67; LAX_RSX_FinalEA_2019.pdf p29','high complex evidence; limited Station L bus crosswalk','Station L node is not a verified individual generating unit'),
'309569':('generation_complex_receiving_node','LA100 names Valley generation site; July Station M(Valley) is an abstracted station','LA100_ch6.txt PDF67','site evidence; limited station/bus crosswalk','No direct proof of independent injection at modeled node'),
'308581':('documented_receiving_distribution_station','RS-Q existing RackB serves San Pedro/Port; not evidence of generation at RS-Q','ZEPEO_MND_2025.pdf p24','high receiving station identity; generation label unsupported','Original in_basin_generation_proxy should be read as supply-boundary assumption, not generator fact')}
rows=[]
for row in s.itertuples():
 d=detail[row.ID];rows.append(dict(July_ID=row.ID,name=row.NAME,owner=row.Owner,voltage=f'{row.MAX_VOLT}/{row.MIN_VOLT}',current_Core_source_flag=True,original_source_type=row.source_type,evidence_class=d[0],external_supply_evidence=d[1],evidence_type=d[2],confidence=d[3],ambiguity=d[4],independent_injection_confirmed='not established',availability_status='scenario assumption; not inferred from document presence'))
pd.DataFrame(rows).to_csv(o/'SOURCE_NODE_EVIDENCE_CROSSWALK.csv',index=False)
(o/'SOURCE_SET_DECISION.json').write_text(json.dumps({'baseline_sources':s.ID.tolist(),'externally_confirmed_subset_created':False,'reason':'Evidence identifies mixed generations sites, receiving stations and import complexes at incompatible asset levels. Exact bus injection and East/West distinctions are incomplete. Selecting only well-documented IDs would conflate document availability with supply availability.','generation_sampling_added':False,'capacity_adequacy_implied':False,'topology_modified':False,'static_single_path_stations':t.index[t.single_path].tolist(),'static_single_upstream_stations':t.index[t.single_upstream_station].tolist()},indent=2))
